export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAILURE = 'GET_SINGLE_PRODUCT_FAILURE';
export const PRODUCT_REVIEW_SUCCESS = 'PRODUCT_REVIEW_SUCCESS';
export const PRODUCT_REVIEW_FAILURE = 'PRODUCT_REVIEW_FAILURE';